-- Atalhos do dashboard: configuráveis por usuário e, sem configuração, ordenados pelo uso real.
--
-- node_dashboard_atalhos: a escolha explícita do usuário (quais atalhos e em que ordem).
--   Sem linhas para o usuário = ele não personalizou, então vale a ordenação automática.
-- node_rota_uso: quantas vezes cada usuário abriu cada tela. Alimenta a ordenação automática —
--   os atalhos mais usados sobem, sem ninguém precisar configurar nada.

CREATE TABLE IF NOT EXISTS node_dashboard_atalhos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  usuario INT NOT NULL,
  chave VARCHAR(40) NOT NULL,
  posicao INT NOT NULL DEFAULT 0,
  CONSTRAINT uq_dashboard_atalho UNIQUE (usuario, chave)
);
CREATE INDEX IF NOT EXISTS idx_dashboard_atalhos_usuario ON node_dashboard_atalhos (usuario, posicao);

CREATE TABLE IF NOT EXISTS node_rota_uso (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  usuario INT NOT NULL,
  rota VARCHAR(60) NOT NULL,
  acessos INT NOT NULL DEFAULT 1,
  ultimo_acesso TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_rota_uso UNIQUE (usuario, rota)
);
CREATE INDEX IF NOT EXISTS idx_rota_uso_usuario ON node_rota_uso (usuario, acessos DESC);
