-- Schema baseline PostgreSQL do saas2026 — fonte única de verdade.
-- Gerado a partir de docker/mysql/init/001-test-schema.sql + migrations/003, 004 e 007,
-- que estavam divergentes: as tabelas fiscais e de folha não existiam no ambiente de teste.
-- Dados de teste ficam em 002-seed-test.sql e NUNCA devem ir para produção.


CREATE TABLE empresas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  cpf VARCHAR(25) NULL,
  telefone VARCHAR(20) NULL,
  email VARCHAR(50) NULL,
  endereco VARCHAR(100) NULL,
  numero VARCHAR(10) NULL,
  bairro VARCHAR(50) NULL,
  cidade VARCHAR(50) NULL,
  estado VARCHAR(50) NULL,
  cep VARCHAR(20) NULL,
  tipo_pessoa VARCHAR(15) NULL,
  data_cad DATE NOT NULL DEFAULT CURRENT_DATE,
  usuario INT NULL,
  complemento VARCHAR(100) NULL,
  dias_teste INT NULL,
  mensalidade DECIMAL(8,2) NULL,
  ativo VARCHAR(5) NOT NULL,
  data_teste DATE NULL,
  plano INT NULL,
  url_site VARCHAR(100) NULL,
  frequencia INT NULL,
  dispositivos INT NULL
);

CREATE TABLE usuarios (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  senha VARCHAR(50) NULL,
  senha_crip VARCHAR(130) NOT NULL,
  nivel VARCHAR(25) NOT NULL,
  ativo VARCHAR(5) NOT NULL,
  telefone VARCHAR(20) NULL,
  endereco VARCHAR(150) NULL,
  foto VARCHAR(100) NULL,
  data DATE NOT NULL,
  data_nasc DATE NULL,
  numero VARCHAR(10) NULL,
  bairro VARCHAR(50) NULL,
  cidade VARCHAR(50) NULL,
  estado VARCHAR(50) NULL,
  cep VARCHAR(20) NULL,
  acessar_painel VARCHAR(5) NULL,
  cpf VARCHAR(20) NULL,
  mostrar_registros VARCHAR(5) NULL,
  complemento VARCHAR(100) NULL,
  comissao DECIMAL(9,2) NULL,
  pix VARCHAR(100) NULL,
  tipo_chave VARCHAR(100) NULL,
  salario DECIMAL(10,2) NULL,
  valor_hora DECIMAL(10,2) NULL,
  hora_entrada TIME NULL,
  hora_saida TIME NULL,
  jornada_horas TIME NULL,
  empresa INT NULL
);

CREATE TABLE acessos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  chave VARCHAR(50) NOT NULL,
  grupo INT NOT NULL,
  pagina VARCHAR(5) NULL
);
CREATE TABLE acessos_sas (LIKE acessos INCLUDING ALL);
CREATE TABLE grupo_acessos_sas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(25) NOT NULL
);
CREATE TABLE usuarios_permissoes (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, usuario INT NOT NULL, permissao INT NOT NULL);
CREATE TABLE usuarios_permissoes_sas (LIKE usuarios_permissoes INCLUDING ALL);

CREATE TABLE clientes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  cpf VARCHAR(25) NULL,
  telefone VARCHAR(20) NULL,
  email VARCHAR(50) NULL,
  endereco VARCHAR(100) NULL,
  numero VARCHAR(10) NULL,
  bairro VARCHAR(50) NULL,
  cidade VARCHAR(50) NULL,
  estado VARCHAR(50) NULL,
  cep VARCHAR(20) NULL,
  tipo_pessoa VARCHAR(15) NULL,
  data_cad DATE NOT NULL,
  data_nasc DATE NULL,
  usuario INT NULL,
  complemento VARCHAR(100) NULL,
  empresa INT NULL,
  marketing VARCHAR(5) NULL,
  senha_crip VARCHAR(150) NULL,
  ativo VARCHAR(5) NULL,
  token VARCHAR(255) NULL,
  foto VARCHAR(100) NULL,
  assinatura VARCHAR(100) NULL,
  api_pagamento_cliente VARCHAR(50) NULL,
  formas_pgto VARCHAR(100) NULL
);

CREATE TABLE fornecedores (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  telefone VARCHAR(50) NOT NULL,
  email VARCHAR(50) NULL,
  endereco VARCHAR(100) NULL,
  pix VARCHAR(50) NULL,
  data DATE NOT NULL,
  numero VARCHAR(10) NULL,
  bairro VARCHAR(50) NULL,
  cidade VARCHAR(50) NULL,
  estado VARCHAR(50) NULL,
  cep VARCHAR(20) NULL,
  cnpj VARCHAR(20) NULL,
  complemento VARCHAR(255) NULL,
  tipo_chave VARCHAR(100) NULL,
  empresa INT NULL,
  ativo VARCHAR(5) NOT NULL DEFAULT 'Sim'
);

CREATE TABLE categorias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  foto VARCHAR(100) NOT NULL DEFAULT 'sem-foto.jpg',
  ativo VARCHAR(5) NOT NULL DEFAULT 'Sim',
  empresa INT NULL,
  icone VARCHAR(60) NULL
);
CREATE TABLE produtos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL,
  nome VARCHAR(50) NOT NULL,
  valor_compra DECIMAL(8,2) NOT NULL,
  valor_venda DECIMAL(8,2) NOT NULL,
  valor_promocional DECIMAL(8,2) NULL,
  estoque INT NOT NULL,
  foto VARCHAR(100) NOT NULL,
  ativo VARCHAR(5) NOT NULL,
  nivel_estoque INT NOT NULL,
  categoria INT NOT NULL,
  sub_categoria VARCHAR(50) NULL,
  fornecedor INT NOT NULL,
  descricao VARCHAR(255) NULL,
  tem_estoque VARCHAR(5) NULL,
  vendas INT NULL,
  empresa INT NULL,
  mostrar_site VARCHAR(5) NULL
);
CREATE TABLE servicos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  valor DECIMAL(8,2) NOT NULL,
  comissao INT NULL,
  dias INT NOT NULL,
  ativo VARCHAR(5) NOT NULL,
  empresa INT NULL,
  foto VARCHAR(100) NULL,
  mostrar_site VARCHAR(5) NULL,
  descricao TEXT NULL
);
CREATE TABLE formas_pgto (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome VARCHAR(50) NOT NULL, taxa INT NULL, empresa INT NULL);

CREATE TABLE pagar (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(100) NULL,
  fornecedor INT NOT NULL,
  funcionario INT NOT NULL,
  valor DECIMAL(8,2) NOT NULL,
  vencimento DATE NOT NULL,
  data_pgto DATE NULL,
  data_lanc DATE NOT NULL,
  forma_pgto INT NOT NULL,
  frequencia INT NOT NULL,
  obs VARCHAR(100) NULL,
  referencia VARCHAR(30) NULL,
  subtotal DECIMAL(8,2) NULL,
  multa DECIMAL(10,2) NULL, juros DECIMAL(10,2) NULL, desconto DECIMAL(10,2) NULL, taxa DECIMAL(10,2) NULL,
  usuario_lanc INT NOT NULL,
  usuario_pgto INT NOT NULL,
  pago VARCHAR(5) NULL,
  caixa INT NULL,
  empresa INT NULL,
  node_status VARCHAR(20) NOT NULL DEFAULT 'ativo',
  node_cancel_reason VARCHAR(255) NULL,
  node_cancelled_at TIMESTAMP NULL,
  node_cancelled_by INT NULL
);
CREATE TABLE receber (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(100) NULL,
  cliente INT NULL,
  valor DECIMAL(8,2) NULL,
  vencimento DATE NULL,
  data_pgto DATE NULL,
  data_lanc DATE NULL,
  forma_pgto INT NULL,
  obs VARCHAR(100) NULL,
  arquivo VARCHAR(100) NULL,
  referencia VARCHAR(30) NULL,
  subtotal DECIMAL(8,2) NULL,
  multa DECIMAL(10,2) NULL, juros DECIMAL(10,2) NULL, desconto DECIMAL(10,2) NULL, taxa DECIMAL(10,2) NULL,
  usuario_lanc INT NULL,
  usuario_pgto INT NULL,
  pago VARCHAR(5) NULL,
  hora TIME NULL,
  empresa INT NULL,
  total_venda DECIMAL(10,2) NULL,
  valor_custo DECIMAL(10,2) NULL,
  cancelada VARCHAR(25) NULL,
  caixa INT NULL,
  node_status VARCHAR(20) NOT NULL DEFAULT 'ativo',
  node_cancel_reason VARCHAR(255) NULL,
  node_cancelled_at TIMESTAMP NULL,
  node_cancelled_by INT NULL
);
CREATE TABLE pagar_sas (LIKE pagar INCLUDING ALL);
CREATE TABLE receber_sas (LIKE receber INCLUDING ALL);

CREATE TABLE planos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NULL,
  valor DECIMAL(10,2) NULL,
  ativo VARCHAR(5) NULL,
  clientes INT NULL,
  usuarios INT NULL,
  dispositivos INT NULL
);
CREATE TABLE planos_itens (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plano INT NULL,
  nome VARCHAR(100) NULL
);
CREATE TABLE recursos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NULL,
  chave VARCHAR(50) NULL,
  -- Agrupam a tabela de comparação de planos da página pública. Ficam no banco (e não no HTML)
  -- para o administrador reorganizar a comparação sem depender de deploy.
  grupo VARCHAR(40) NULL,
  posicao INT NULL
);
CREATE TABLE planos_recursos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plano INT NULL,
  recurso INT NULL
);
CREATE TABLE clientes_recursos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NULL,
  recurso INT NULL
);
CREATE TABLE alertas_sas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(100) NULL,
  texto TEXT NULL,
  ativo VARCHAR(5) NULL,
  data DATE NULL
);

CREATE TABLE itens_venda (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto INT NOT NULL,
  valor DECIMAL(8,2) NOT NULL,
  quantidade INT NOT NULL,
  total DECIMAL(8,2) NOT NULL,
  id_venda INT NOT NULL,
  funcionario INT NOT NULL,
  empresa INT NULL,
  tipo VARCHAR(25) NULL,
  comissao_paga VARCHAR(5) NOT NULL DEFAULT 'Não',
  comissao_paga_em TIMESTAMP NULL,
  comissao_paga_por INT NULL
);
CREATE TABLE entradas (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, produto INT NOT NULL, quantidade INT NOT NULL, motivo VARCHAR(100) NOT NULL, usuario INT NOT NULL, data DATE NOT NULL, empresa INT NULL);
CREATE TABLE saidas (LIKE entradas INCLUDING ALL);

CREATE TABLE orcamentos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente INT NOT NULL,
  data DATE NOT NULL,
  data_entrega DATE NOT NULL,
  dias_validade INT NOT NULL,
  valor DECIMAL(8,2) NOT NULL,
  desconto INT NOT NULL,
  tipo_desconto VARCHAR(20) NOT NULL,
  subtotal DECIMAL(8,2) NOT NULL,
  obs VARCHAR(255) NULL,
  status VARCHAR(20) NOT NULL,
  total_produtos DECIMAL(8,2) NULL,
  total_servicos DECIMAL(8,2) NULL,
  funcionario INT NOT NULL,
  frete DECIMAL(8,2) NOT NULL,
  equipamento VARCHAR(50) NULL,
  marca VARCHAR(50) NULL,
  modelo VARCHAR(50) NULL,
  defeito VARCHAR(1000) NULL,
  condicoes VARCHAR(2000) NULL,
  acessorios VARCHAR(1000) NULL,
  laudo VARCHAR(1000) NULL,
  senha_ap VARCHAR(50) NULL,
  mao_obra DECIMAL(8,2) NULL,
  vall DECIMAL(8,2) NULL,
  empresa INT NULL
);
CREATE TABLE os (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente INT NOT NULL,
  data DATE NOT NULL,
  data_entrega DATE NOT NULL,
  dias_validade INT NULL,
  valor DECIMAL(8,2) NOT NULL,
  desconto INT NOT NULL,
  tipo_desconto VARCHAR(20) NOT NULL,
  subtotal DECIMAL(8,2) NOT NULL,
  obs VARCHAR(255) NULL,
  status VARCHAR(20) NOT NULL,
  total_produtos DECIMAL(8,2) NOT NULL,
  total_servicos DECIMAL(8,2) NOT NULL,
  funcionario INT NOT NULL,
  frete DECIMAL(8,2) NOT NULL,
  tecnico INT NOT NULL,
  equipamento VARCHAR(255) NULL,
  marca VARCHAR(255) NULL,
  modelo VARCHAR(255) NULL,
  defeito VARCHAR(1000) NULL,
  laudo VARCHAR(2000) NULL,
  condicoes VARCHAR(2000) NULL,
  acessorios VARCHAR(1000) NULL,
  orcamento INT NULL,
  mao_obra DECIMAL(8,2) NULL,
  val_entrada DECIMAL(8,2) NULL,
  vall DECIMAL(8,2) NULL,
  dias_garantia VARCHAR(50) NULL,
  senha_ap VARCHAR(50) NULL,
  forma_pgto VARCHAR(20) NULL,
  pago VARCHAR(5) NULL,
  empresa INT NULL
);
CREATE TABLE produtos_orc (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto INT NOT NULL,
  orcamento INT NULL,
  funcionario INT NOT NULL,
  quantidade INT NOT NULL,
  valor DECIMAL(8,2) NOT NULL,
  total DECIMAL(8,2) NOT NULL,
  os INT NULL
);
CREATE TABLE servicos_orc (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  servico INT NOT NULL,
  orcamento INT NULL,
  funcionario INT NOT NULL,
  quantidade INT NOT NULL,
  valor DECIMAL(8,2) NOT NULL,
  total DECIMAL(8,2) NOT NULL,
  os INT NULL,
  cliente INT NULL,
  data DATE NULL,
  equipamento VARCHAR(100) NULL,
  modelo VARCHAR(100) NULL,
  subtotal DECIMAL(8,2) NULL
);

CREATE TABLE sub_categorias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  ativo VARCHAR(5) NOT NULL DEFAULT 'Sim',
  foto VARCHAR(100) NULL,
  empresa INT NULL
);
CREATE TABLE marcas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  ativo VARCHAR(5) NOT NULL DEFAULT 'Sim',
  empresa INT NULL
);
CREATE TABLE equipamentos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  ativo VARCHAR(5) NOT NULL DEFAULT 'Sim',
  empresa INT NULL
);
CREATE TABLE modelos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  ativo VARCHAR(5) NOT NULL DEFAULT 'Sim',
  marca VARCHAR(100) NULL,
  equipamento VARCHAR(100) NULL,
  empresa INT NULL
);
CREATE TABLE cargos (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome VARCHAR(50) NOT NULL, empresa INT NULL);
CREATE TABLE frequencias (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, frequencia VARCHAR(25) NOT NULL, dias INT NOT NULL, empresa INT NULL);
CREATE TABLE plano_contas (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome VARCHAR(150) NULL, empresa INT NULL);
CREATE TABLE cupons (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL,
  valor DECIMAL(8,2) NOT NULL,
  data DATE NULL,
  quantidade INT NULL,
  valor_minimo DECIMAL(8,2) NULL,
  tipo VARCHAR(20) NULL,
  empresa INT NULL
);
CREATE TABLE contratos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modelo VARCHAR(50) NOT NULL,
  texto TEXT NOT NULL,
  mostrar_modelos VARCHAR(5) NULL,
  empresa INT NULL
);
CREATE TABLE anotacoes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(250) NOT NULL,
  msg TEXT NOT NULL,
  usuario INT NOT NULL,
  data DATE NOT NULL,
  mostrar_home VARCHAR(5) NOT NULL,
  privado VARCHAR(5) NOT NULL,
  empresa INT NULL
);
CREATE TABLE tarefas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario INT NOT NULL,
  usuario_lanc INT NOT NULL,
  data DATE NOT NULL,
  hora TIME NOT NULL,
  hora_mensagem TIME NULL,
  descricao VARCHAR(2000) NULL,
  status VARCHAR(20) NULL,
  hash VARCHAR(100) NULL,
  prioridade VARCHAR(25) NULL,
  titulo VARCHAR(255) NULL,
  recorrencia INT NULL,
  empresa INT NULL
);
CREATE TABLE tarefas_clientes (LIKE tarefas INCLUDING ALL);
CREATE TABLE chamados (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  data DATE NOT NULL,
  titulo VARCHAR(255) NULL,
  texto TEXT NULL,
  status VARCHAR(25) NULL,
  respondido VARCHAR(5) NULL
);
CREATE TABLE chamados_respostas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  data DATE NOT NULL,
  hora TIME NOT NULL,
  usuario INT NOT NULL,
  texto TEXT NOT NULL,
  chamado INT NOT NULL
);
CREATE TABLE marketing (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data DATE NOT NULL,
  data_envio DATE NULL,
  envios INT NULL,
  titulo VARCHAR(100) NULL,
  mensagem2 TEXT NULL,
  mensagem TEXT NULL,
  arquivo VARCHAR(100) NULL,
  audio VARCHAR(100) NULL,
  forma_envio VARCHAR(50) NULL,
  documento VARCHAR(100) NULL,
  ultimo_registro INT NULL,
  empresa INT NULL,
  dispositivo VARCHAR(35) NULL,
  total_disparos INT NULL
);
CREATE TABLE grupos_disparos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NULL,
  ativo VARCHAR(5) NULL,
  nome VARCHAR(100) NULL
);
CREATE TABLE grupos_clientes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NULL,
  grupo INT NULL,
  cliente INT NULL,
  CONSTRAINT uq_group_client UNIQUE (empresa, grupo, cliente)
);
CREATE TABLE dispositivos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telefone VARCHAR(20) NULL,
  appkey VARCHAR(40) NULL,
  status VARCHAR(50) NOT NULL,
  status_api VARCHAR(100) NULL,
  horario TIMESTAMP NULL,
  empresa INT NULL
);
CREATE TABLE node_marketing_dispatch (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campanha INT NOT NULL,
  cliente INT NOT NULL,
  nome VARCHAR(100) NULL,
  telefone VARCHAR(20) NOT NULL,
  mensagem TEXT NOT NULL,
  empresa INT NOT NULL,
  status VARCHAR(20) NOT NULL,
  tentativas INT NOT NULL DEFAULT 0,
  agendado_para TIMESTAMP NOT NULL,
  enviado_em TIMESTAMP NULL,
  erro VARCHAR(500) NULL,
  consentimento_confirmado VARCHAR(5) NOT NULL,
  criado_em TIMESTAMP NOT NULL,
  atualizado_em TIMESTAMP NOT NULL,
  CONSTRAINT uq_campaign_client_schedule UNIQUE (campanha, cliente, agendado_para)
);
CREATE TABLE caixas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operador INT NOT NULL,
  data_abertura DATE NOT NULL,
  data_fechamento DATE NULL,
  valor_abertura DECIMAL(10,2) NOT NULL,
  valor_fechamento DECIMAL(10,2) NULL,
  quebra DECIMAL(10,2) NULL,
  usuario_abertura INT NOT NULL,
  usuario_fechamento INT NULL,
  obs VARCHAR(255) NULL,
  sangrias DECIMAL(10,2) NULL,
  empresa INT NULL
);
CREATE TABLE sangrias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario INT NOT NULL,
  valor DECIMAL(10,2) NOT NULL,
  data DATE NOT NULL,
  hora TIME NOT NULL,
  caixa INT NOT NULL
);
CREATE TABLE cobrancas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente INT NOT NULL,
  valor DECIMAL(10,2) NOT NULL,
  juros DECIMAL(10,2) NULL,
  multa DECIMAL(10,2) NULL,
  data DATE NOT NULL,
  usuario INT NOT NULL,
  obs VARCHAR(255) NULL,
  data_venc DATE NOT NULL,
  frequencia VARCHAR(25) NOT NULL,
  valor_parcela DECIMAL(10,2) NULL,
  descricao VARCHAR(50) NULL,
  parcelas INT NULL,
  empresa INT NULL,
  api_pagamento_conta VARCHAR(50) NULL,
  pgtos_aceitaveis VARCHAR(100) NULL,
  node_status VARCHAR(20) NOT NULL DEFAULT 'ativo'
);
CREATE TABLE node_purchases (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  fornecedor INT NOT NULL,
  usuario INT NOT NULL,
  forma_pgto INT NULL,
  data DATE NOT NULL,
  vencimento DATE NOT NULL,
  total DECIMAL(12,2) NOT NULL,
  pago VARCHAR(5) NOT NULL,
  status VARCHAR(20) NOT NULL,
  observacoes VARCHAR(500) NULL,
  payable_id INT NULL,
  criado_em TIMESTAMP NOT NULL,
  cancelado_em TIMESTAMP NULL,
  cancelado_por INT NULL,
  motivo_cancelamento VARCHAR(255) NULL
);
CREATE TABLE node_purchase_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra INT NOT NULL,
  produto INT NOT NULL,
  quantidade INT NOT NULL,
  valor_unitario DECIMAL(12,2) NOT NULL,
  total DECIMAL(12,2) NOT NULL
);
CREATE TABLE node_contracts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  cliente INT NOT NULL,
  modelo_id INT NULL,
  titulo VARCHAR(150) NOT NULL,
  conteudo TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  inicio DATE NULL,
  fim DATE NULL,
  valor DECIMAL(12,2) NULL,
  criado_por INT NOT NULL,
  criado_em TIMESTAMP NOT NULL,
  atualizado_em TIMESTAMP NOT NULL
);
CREATE TABLE node_contract_signatures (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  contrato INT NOT NULL,
  cliente INT NOT NULL,
  assinado_por VARCHAR(100) NOT NULL,
  user_agent VARCHAR(255) NULL,
  assinado_em TIMESTAMP NOT NULL,
  CONSTRAINT uq_contract_signature UNIQUE (empresa, contrato, cliente)
);
CREATE TABLE node_recurring_generated (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  cobranca INT NOT NULL,
  recebivel INT NOT NULL,
  vencimento DATE NOT NULL,
  criado_em TIMESTAMP NOT NULL,
  CONSTRAINT uq_recurring_due UNIQUE (empresa, cobranca, vencimento)
);
CREATE TABLE node_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  entidade VARCHAR(40) NOT NULL,
  entidade_id INT NOT NULL,
  nome_original VARCHAR(180) NOT NULL,
  nome_armazenado VARCHAR(80) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  tamanho INT NOT NULL,
  criado_por INT NOT NULL,
  criado_em TIMESTAMP NOT NULL
);
CREATE TABLE node_store_orders (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  cliente INT NOT NULL,
  recebivel INT NOT NULL,
  token_acompanhamento CHAR(36) NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL,
  desconto DECIMAL(12,2) NOT NULL,
  total DECIMAL(12,2) NOT NULL,
  cupom VARCHAR(50) NULL,
  status VARCHAR(30) NOT NULL,
  observacoes VARCHAR(500) NULL,
  criado_em TIMESTAMP NOT NULL,
  atualizado_em TIMESTAMP NOT NULL,
  CONSTRAINT uq_store_tracking UNIQUE (token_acompanhamento)
);
CREATE TABLE node_store_order_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido INT NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  item_id INT NOT NULL,
  nome VARCHAR(100) NOT NULL,
  quantidade INT NOT NULL,
  valor_unitario DECIMAL(12,2) NOT NULL,
  total DECIMAL(12,2) NOT NULL
);
CREATE TABLE jornada (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  funcionario INT NOT NULL,
  data DATE NOT NULL,
  entrada TIME NULL,
  entrada_almoco TIME NULL,
  saida_almoco TIME NULL,
  saida TIME NULL,
  total_horas TIME NULL,
  intervalo TIME NULL,
  hora_extra TIME NULL,
  folga VARCHAR(5) NOT NULL DEFAULT 'Não',
  feriado VARCHAR(5) NOT NULL DEFAULT 'Não',
  falta VARCHAR(5) NOT NULL DEFAULT 'Não',
  data_lanc DATE NOT NULL,
  usuario_lanc INT NOT NULL,
  empresa INT NULL,
  CONSTRAINT uq_jornada_funcionario_data UNIQUE (empresa, funcionario, data)
);
CREATE TABLE site (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NULL,
  titulo VARCHAR(255) NULL,
  subtitulo VARCHAR(255) NULL,
  botao1 VARCHAR(80) NULL,
  botao2 VARCHAR(80) NULL,
  botao3 VARCHAR(80) NULL,
  -- Selos de confiança abaixo da chamada (landing de planos e site da loja).
  item1 VARCHAR(100) NULL,
  item2 VARCHAR(100) NULL,
  item3 VARCHAR(100) NULL,
  logo VARCHAR(100) NULL,
  logo_topo VARCHAR(5) NULL,
  fundo_topo VARCHAR(100) NULL,
  fundo_topo_mobile VARCHAR(100) NULL,
  titulo_recursos VARCHAR(255) NULL,
  titulo_perguntas VARCHAR(255) NULL,
  titulo_rodape VARCHAR(255) NULL,
  descricao_rodape TEXT NULL,
  botao_rodape VARCHAR(100) NULL,
  link_rodape VARCHAR(255) NULL,
  descricao_site TEXT NULL,
  video_site VARCHAR(255) NULL
);
CREATE TABLE config (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50) NULL,
  email VARCHAR(50) NULL,
  telefone VARCHAR(20) NULL,
  endereco VARCHAR(100) NULL,
  instagram VARCHAR(100) NULL,
  cnpj VARCHAR(25) NULL,
  cidade_sistema VARCHAR(50) NULL,
  marca_dagua VARCHAR(5) NULL,
  assinatura_recibo VARCHAR(5) NULL,
  impressao_automatica VARCHAR(5) NULL,
  abertura_caixa VARCHAR(5) NULL,
  dias_comissao INT NULL,
  assinatura_cliente VARCHAR(5) NULL,
  cobrar_automaticamente VARCHAR(5) NULL,
  cobrar_duas_vezes VARCHAR(5) NULL,
  pagina_entrada VARCHAR(25) NULL,
  url_site VARCHAR(255) NULL,
  meta_descricao VARCHAR(255) NULL,
  -- Segredos de integração ficam cifrados em repouso (AES-256-GCM/base64), por isso TEXT:
  -- a cifra é bem maior que o valor original e um VARCHAR curto truncaria a chave em silêncio.
  token_whatsapp TEXT NULL,
  instancia_whatsapp VARCHAR(70) NULL,
  access_token TEXT NULL,
  public_key VARCHAR(255) NULL, -- chave pública do Mercado Pago: não é segredo, fica em texto
  chave_api_asaas TEXT NULL,
  api_whatsapp VARCHAR(60) NULL,
  api_pagamento VARCHAR(30) NULL,
  dados_pagamento TEXT NULL,
  multa_atraso DECIMAL(8,2) NULL,
  juros_atraso DECIMAL(8,2) NULL,
  dias_lembrete INT NULL,
  mao_obra_orc VARCHAR(100) NULL, senha_aparelho_orc VARCHAR(100) NULL, defeito_orc VARCHAR(100) NULL,
  avarias_orc VARCHAR(100) NULL, acessorios_orc VARCHAR(100) NULL, laudo_orc VARCHAR(100) NULL,
  mao_obra_os VARCHAR(100) NULL, senha_aparelho_os VARCHAR(100) NULL, defeito_os VARCHAR(100) NULL,
  avarias_os VARCHAR(100) NULL, acessorios_os VARCHAR(100) NULL, laudo_os VARCHAR(100) NULL,
  empresa INT NULL
);
CREATE TABLE recursos_site (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo_recurso VARCHAR(150) NULL,
  icone_recurso VARCHAR(100) NULL,
  descricao_recurso VARCHAR(255) NULL,
  empresa INT NOT NULL,
  posicao_recurso INT NULL
);
CREATE TABLE perguntas_site (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo_pergunta VARCHAR(150) NULL,
  descricao_pergunta TEXT NULL,
  empresa INT NOT NULL,
  posicao_pergunta INT NULL
);
CREATE TABLE videos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(255) NULL,
  link VARCHAR(255) NULL,
  ordem INT NULL
);

CREATE TABLE node_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  usuario INT NOT NULL,
  acao VARCHAR(40) NOT NULL,
  entidade VARCHAR(40) NOT NULL,
  entidade_id INT NOT NULL,
  motivo VARCHAR(255) NULL,
  detalhes JSONB NULL,
  criado_em TIMESTAMP NOT NULL
);

-- Tabelas fiscais e de folha (migrações 003/004/007), ausentes do seed original.
-- Executar uma única vez, depois de 002_legacy_parity.sql.
-- Fundação fiscal para emissão de NFS-e (Padrao Nacional / SEFIN Nacional) e NF-e (SEFAZ).
-- Nao contem dados, credenciais nem certificados. O certificado digital A1 e a sua senha
-- NUNCA ficam neste banco: o arquivo fica em storage protegido fora do repositorio e a
-- senha em variavel de ambiente ou cofre. Aqui guardamos apenas referencias.

-- 1. Emitente: campos fiscais que faltam em empresas.
ALTER TABLE empresas
  ADD COLUMN cnpj VARCHAR(18) NULL,
  ADD COLUMN razao_social VARCHAR(150) NULL,
  ADD COLUMN nome_fantasia VARCHAR(150) NULL,
  ADD COLUMN inscricao_estadual VARCHAR(20) NULL,
  ADD COLUMN inscricao_municipal VARCHAR(20) NULL,
  ADD COLUMN regime_tributario VARCHAR(30) NULL,
  ADD COLUMN cnae VARCHAR(10) NULL,
  ADD COLUMN codigo_ibge CHAR(7) NULL;

-- 2. Tomador/destinatario: campos fiscais que faltam em clientes.
ALTER TABLE clientes
  ADD COLUMN cnpj VARCHAR(18) NULL,
  ADD COLUMN inscricao_estadual VARCHAR(20) NULL,
  ADD COLUMN ind_ie_dest VARCHAR(1) NULL,
  ADD COLUMN codigo_ibge CHAR(7) NULL;

-- 3. Itens de venda: campos fiscais em produtos. A venda referencia produtos, entao a
--    classificacao fiscal (mercadoria ou servico) e os campos de cada caso ficam aqui.
--    tipo_fiscal = 'mercadoria' usa os campos de NF-e; 'servico' usa os campos de NFS-e.
ALTER TABLE produtos
  ADD COLUMN tipo_fiscal VARCHAR(12) NOT NULL DEFAULT 'mercadoria',
  ADD COLUMN ncm VARCHAR(8) NULL,
  ADD COLUMN cest VARCHAR(7) NULL,
  ADD COLUMN cfop VARCHAR(4) NULL,
  ADD COLUMN origem VARCHAR(1) NULL,
  ADD COLUMN cst_csosn VARCHAR(4) NULL,
  ADD COLUMN unidade_fiscal VARCHAR(6) NULL,
  ADD COLUMN aliq_icms DECIMAL(6,2) NULL,
  ADD COLUMN aliq_pis DECIMAL(6,2) NULL,
  ADD COLUMN aliq_cofins DECIMAL(6,2) NULL,
  ADD COLUMN codigo_lc116 VARCHAR(10) NULL,
  ADD COLUMN codigo_tributacao_municipio VARCHAR(20) NULL,
  ADD COLUMN aliquota_iss DECIMAL(6,2) NULL;

-- 4. Servico (NFS-e): campos fiscais em servicos.
ALTER TABLE servicos
  ADD COLUMN codigo_lc116 VARCHAR(10) NULL,
  ADD COLUMN codigo_tributacao_municipio VARCHAR(20) NULL,
  ADD COLUMN aliquota_iss DECIMAL(6,2) NULL,
  ADD COLUMN cnae VARCHAR(10) NULL,
  ADD COLUMN iss_retido VARCHAR(5) NOT NULL DEFAULT 'Nao';

-- 5. Configuracao fiscal por empresa (multi-tenant). Ambiente comeca em homologacao.
--    certificado_ref: caminho do arquivo do certificado em storage protegido (nunca o conteudo).
--    certificado_senha_ref: nome da variavel de ambiente/cofre que guarda a senha (nunca a senha).
CREATE TABLE node_fiscal_config (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  ambiente VARCHAR(15) NOT NULL DEFAULT 'homologacao',
  emite_nfse VARCHAR(5) NOT NULL DEFAULT 'Sim',
  emite_nfe VARCHAR(5) NOT NULL DEFAULT 'Nao',
  certificado_ref VARCHAR(255) NULL,
  certificado_senha_ref VARCHAR(100) NULL,
  certificado_validade DATE NULL,
  regime_especial VARCHAR(30) NULL,
  incentivo_fiscal VARCHAR(5) NOT NULL DEFAULT 'Nao',
  atualizado_por INT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_fiscal_config_empresa UNIQUE (empresa)
);

-- 6. Controle de numeracao por empresa, modelo e serie.
CREATE TABLE node_fiscal_numeracao (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  modelo VARCHAR(10) NOT NULL,
  serie VARCHAR(5) NOT NULL DEFAULT '1',
  ultimo_numero INT NOT NULL DEFAULT 0,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_fiscal_numeracao UNIQUE (empresa, modelo, serie)
);

-- 7. Documentos fiscais emitidos ou em processamento.
--    referencia: uuid gerado na solicitacao, usado como chave de idempotencia da submissao.
--    chave_acesso: 44 posicoes na NF-e, ate 50 na NFS-e do Padrao Nacional.
--    xml_path/pdf_path: caminhos em storage protegido para o XML autorizado e o DANFE/DANFSE.
CREATE TABLE node_fiscal_documentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  modelo VARCHAR(10) NOT NULL,
  venda INT NULL,
  cliente INT NULL,
  referencia CHAR(36) NOT NULL,
  numero INT NULL,
  serie VARCHAR(5) NULL,
  chave_acesso VARCHAR(50) NULL,
  protocolo VARCHAR(50) NULL,
  status VARCHAR(15) NOT NULL DEFAULT 'pendente',
  ambiente VARCHAR(15) NOT NULL DEFAULT 'homologacao',
  valor_total DECIMAL(12,2) NULL,
  motivo_rejeicao VARCHAR(500) NULL,
  xml_path VARCHAR(255) NULL,
  pdf_path VARCHAR(255) NULL,
  tentativas INT NOT NULL DEFAULT 0,
  data_emissao TIMESTAMP NULL,
  criado_por INT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_fiscal_doc_referencia UNIQUE (empresa, referencia),
  CONSTRAINT uq_fiscal_doc_chave UNIQUE (chave_acesso)
);

-- 8. Itens fiscais do documento, com os valores e tributos aplicados por item.
CREATE TABLE node_fiscal_documento_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documento BIGINT NOT NULL,
  descricao VARCHAR(180) NOT NULL,
  quantidade DECIMAL(12,4) NOT NULL DEFAULT 1,
  valor_unitario DECIMAL(12,2) NOT NULL,
  valor_total DECIMAL(12,2) NOT NULL,
  ncm_lc116 VARCHAR(10) NULL,
  cfop VARCHAR(4) NULL,
  cst_csosn VARCHAR(4) NULL,
  aliquota DECIMAL(6,2) NULL,
  tributo VARCHAR(10) NULL
);

-- 9. Eventos fiscais (cancelamento, correcao) com rastreio e auditoria.
CREATE TABLE node_fiscal_eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  documento BIGINT NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  status VARCHAR(15) NOT NULL DEFAULT 'pendente',
  motivo VARCHAR(500) NULL,
  protocolo VARCHAR(50) NULL,
  xml_path VARCHAR(255) NULL,
  criado_por INT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Executar uma única vez, depois de 003_fiscal.sql.
-- Guarda a senha do certificado cifrada no banco (AES-256-GCM, chave fora do banco) e o nome
-- original do arquivo. O conteúdo do certificado continua fora do repositório, em storage
-- protegido. Nada de senha em texto.

ALTER TABLE node_fiscal_config
  ADD COLUMN certificado_senha_cifrada TEXT NULL,
  ADD COLUMN certificado_nome VARCHAR(180) NULL;

-- Executar uma única vez, depois de 006_usuarios_teste.sql.
-- Lançamentos manuais da folha (proventos e descontos) por funcionário e competência, para
-- ajustar o total estimado. Os valores são informados pelo operador; o sistema não calcula
-- encargos legais (INSS/FGTS/IRRF), que dependem de tabelas trabalhistas e validação contábil.

CREATE TABLE node_folha_lancamentos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa INT NOT NULL,
  funcionario INT NOT NULL,
  competencia CHAR(7) NOT NULL,
  tipo VARCHAR(10) NOT NULL,
  descricao VARCHAR(120) NOT NULL,
  valor DECIMAL(12,2) NOT NULL,
  criado_por INT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Uma linha de conteúdo de site por empresa (a landing do SaaS é a da empresa 0). O índice único
-- é o que deixa o painel gravar com ON CONFLICT — cria na primeira vez, atualiza nas seguintes.
CREATE UNIQUE INDEX uq_site_empresa ON site (empresa);

CREATE INDEX idx_marketing_due ON node_marketing_dispatch (empresa, status, agendado_para);
CREATE INDEX idx_attachments_record ON node_attachments (empresa, entidade, entidade_id);
CREATE INDEX idx_store_company_date ON node_store_orders (empresa, criado_em);
CREATE INDEX idx_store_items_order ON node_store_order_items (pedido);
CREATE INDEX idx_node_audit_tenant ON node_audit_log (empresa, entidade, entidade_id);
CREATE INDEX idx_fiscal_doc_status ON node_fiscal_documentos (empresa, status);
CREATE INDEX idx_fiscal_doc_venda ON node_fiscal_documentos (empresa, venda);
CREATE INDEX idx_fiscal_doc_modelo ON node_fiscal_documentos (empresa, modelo, criado_em);
CREATE INDEX idx_fiscal_item_documento ON node_fiscal_documento_itens (documento);
CREATE INDEX idx_fiscal_evento_documento ON node_fiscal_eventos (empresa, documento);
CREATE INDEX idx_folha_lanc ON node_folha_lancamentos (empresa, funcionario, competencia);

-- Substitui o ON UPDATE CURRENT_TIMESTAMP do MySQL, que o Postgres não tem.
CREATE OR REPLACE FUNCTION set_atualizado_em() RETURNS trigger AS $$
BEGIN
  NEW.atualizado_em = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_fiscal_config_atualizado BEFORE UPDATE ON node_fiscal_config
  FOR EACH ROW EXECUTE FUNCTION set_atualizado_em();
CREATE TRIGGER trg_fiscal_numeracao_atualizado BEFORE UPDATE ON node_fiscal_numeracao
  FOR EACH ROW EXECUTE FUNCTION set_atualizado_em();
CREATE TRIGGER trg_fiscal_documentos_atualizado BEFORE UPDATE ON node_fiscal_documentos
  FOR EACH ROW EXECUTE FUNCTION set_atualizado_em();


-- Correções de modelo (o banco nasce vazio, então não há dado a migrar).
ALTER TABLE jornada
  ALTER COLUMN total_horas TYPE INTERVAL USING total_horas::interval,
  ALTER COLUMN hora_extra  TYPE INTERVAL USING hora_extra::interval,
  ALTER COLUMN intervalo   TYPE INTERVAL USING intervalo::interval;

ALTER TABLE cobrancas
  ALTER COLUMN frequencia TYPE INTEGER USING NULLIF(frequencia, '')::integer;

