const cors = require('cors');
const express = require('express');
const helmet = require('helmet');
const path = require('node:path');
const { z } = require('zod');
const { errorMap } = require('./config/zod-pt');
// Mensagens de validação em português para toda a aplicação (evita os textos padrão em inglês).
z.setErrorMap(errorMap);
const { env } = require('./config/env');
const { errorHandler, notFound } = require('./middlewares/error-handler');
const healthRoutes = require('./modules/health/health.routes');
const authRoutes = require('./modules/auth/auth.routes');
const userRoutes = require('./modules/users/users.routes');
const clientRoutes = require('./modules/clients/clients.routes');
const catalogRoutes = require('./modules/catalog/catalog.routes');
const financeRoutes = require('./modules/finance/finance.routes');
const inventoryRoutes = require('./modules/inventory/inventory.routes');
const workRoutes = require('./modules/work/work.routes');
const reportsRoutes = require('./modules/reports/reports.routes');
const salesRoutes = require('./modules/sales/sales.routes');
const referenceRoutes = require('./modules/reference/reference.routes');
const collaborationRoutes = require('./modules/collaboration/collaboration.routes');
const marketingRoutes = require('./modules/marketing/marketing.routes');
const operationsRoutes = require('./modules/operations/operations.routes');
const hrRoutes = require('./modules/hr/hr.routes');
const contentRoutes = require('./modules/content/content.routes');
const fileRoutes = require('./modules/files/files.routes');
const portalRoutes = require('./modules/portal/portal.routes');
const adminRoutes = require('./modules/admin/admin.routes');
const publicRoutes = require('./modules/public/public.routes');
const storeRoutes = require('./modules/store/store.routes');
const fiscalRoutes = require('./modules/fiscal/fiscal.routes');
const mediaRoutes = require('./modules/catalog/media.routes');
const webhookRoutes = require('./modules/webhooks/payments.routes');

const app = express();

app.use(helmet());
app.use(cors({ origin: env.corsOrigin }));
app.use(express.json({ limit: '1mb' }));
app.use(express.static(path.join(__dirname, '..', 'public')));
app.use('/api/media', mediaRoutes);
// Público por natureza: quem chama é o servidor do provedor de pagamento, sem sessão. A verificação
// de autenticidade é por assinatura, dentro da própria rota.
app.use('/api/webhooks', webhookRoutes);
app.use('/api/health', healthRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/users', userRoutes);
app.use('/api/clients', clientRoutes);
app.use('/api/catalog', catalogRoutes);
app.use('/api/finance', financeRoutes);
app.use('/api/inventory', inventoryRoutes);
app.use('/api/work', workRoutes);
app.use('/api/reports', reportsRoutes);
app.use('/api/sales', salesRoutes);
app.use('/api/reference', referenceRoutes);
app.use('/api/collaboration', collaborationRoutes);
app.use('/api/marketing', marketingRoutes);
app.use('/api/operations', operationsRoutes);
app.use('/api/hr', hrRoutes);
app.use('/api/content', contentRoutes);
app.use('/api/files', fileRoutes);
app.use('/api/client', portalRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/public', publicRoutes);
app.use('/api/store', storeRoutes);
app.use('/api/fiscal', fiscalRoutes);
app.use(notFound);
app.use(errorHandler);

module.exports = { app };
